version: '3'

services: 
    usersDb:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: root 
            MYSQL_DATABASE: users
        ports: 
            - "3306:3306"
        volumes:
            - ./bdd:/docker-entrypoint-initdb.d:ro 
        
    web_slay:
        build:
            context: ./web_service
            dockerfile: Dockerfile
        environment: 
            FLASK_ENV: development
            FLASK_APP: app.py
        ports:
            - "5000:5000"

    site_web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "80:80"